[package]
name = "pass-git-credential-helper"
version = "0.1.0"
authors = ["lucdew <lucdew@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = "2.33.0"

